# elastic.example.com HTTP
server {
    listen 9200;

    server_name elastic.example.com;

    status_zone elastic-VirtualServer;

    # Server specific logging
    access_log  /var/log/nginx/elastic.example.com.log main; 
    error_log   /var/log/nginx/elastic.example.com_error.log info; 

    location / {
        
        # Including best-practice headers
        include includes/proxy_headers.conf;

        status_zone /;

        proxy_pass http://elastic_backend;
        health_check uri=/_cluster/health;
    }

}
